import type { AppLocale } from "../types";

export const en = {
  tagline: "Monitor input switching",
  devices: "Devices", monitors: "Monitors", settings: "Settings",
  devicesDescription: "Create devices, then assign monitor inputs and a shortcut to each one",
  monitorsDescription: "Scan monitors and assign each physical input to a device",
  settingsDescription: "Configure how SoftKVM looks and works",
  rescan: "Scan again", scanning: "Scanning monitors", scanningDescription: "Reading physical monitors and input sources through DDC/CI. Some monitors may take a moment to respond.", detecting: "Detecting…",
  newDeviceName: "New device name", newDevicePlaceholder: "For example: PC 1, Xbox, Nintendo Switch", createDevice: "Create device",
  noDevices: "No devices yet", noDevicesDescription: "Create a PC or console, then assign monitor inputs to it under Monitors.",
  assignedMonitors: "Assigned to {count} monitor(s)", portMappings: "Input mappings", notAssignedHint: "Not assigned yet. Open Monitors to assign inputs.", switchToDevice: "Switch to this device",
  noMonitorsMapped: "No monitors were detected, so device mappings may be temporarily unavailable.",
  deleteDeviceTitle: "Delete “{name}”?", deleteDeviceDescription: "This also removes this device's input assignments and shortcut. It does not affect the monitors themselves.", cancel: "Cancel", confirmDelete: "Delete",
  noMonitors: "No monitors found", noMonitorsDescription: "Make sure the monitors are connected and DDC/CI is enabled in their OSD menus.", scanMonitors: "Scan monitors",
  inputsDetected: "Inputs detected", compatibilityMode: "Compatibility mode", monitorNumber: "Monitor {number}", currentInput: "Current {input}", monitorName: "Monitor name", physicalChannel: "Physical channel {number}",
  compatibilityInputs: "Fallback inputs when scanning fails", compatibilityExpanded: "These are common candidates. You can collapse them at any time.", compatibilityCollapsed: "{count} candidate inputs hidden. Click to expand.",
  unassignedDevice: "Unassigned", noAssignableDevices: "There are no devices to assign. Create one under Devices first.", technicalInfo: "Technical information", noCapabilities: "The monitor did not return a capabilities string.",
  appearance: "Appearance", appearanceDescription: "Choose the accent color used for buttons, selections, and focus rings.", themeColor: "Accent color",
  themeCyan: "Cyan", themeBlue: "Blue", themeEmerald: "Green", themeOrange: "Orange", themeZinc: "Neutral",
  language: "Language", languageDescription: "Choose the interface language. System automatically follows Windows.", followSystem: "Use system language",
  systemBehavior: "System behavior", systemBehaviorDescription: "Control how SoftKVM runs with Windows.", autostart: "Launch at startup", autostartDescription: "Run SoftKVM after signing in to Windows so device shortcuts are always available.",
  minimize: "Minimize", close: "Close", dismiss: "Dismiss",
  trayDevices: "Switch device", trayNoDevices: "No devices", trayShow: "Show SoftKVM", trayQuit: "Quit", traySyncFailed: "Could not update the tray menu: {error}",
  pressShortcut: "Press a shortcut…", bindShortcut: "Set shortcut", clearShortcut: "Clear shortcut",
  scanNone: "No accessible physical monitors were found. Check the connections and graphics driver.", scanComplete: "Scan complete. Found {count} physical monitor(s).",
  autostartReadFailed: "Could not read startup status: {error}", autostartChangeFailed: "Could not change startup behavior: {error}",
  deviceNoRoutes: "{name} has no monitor inputs assigned.", deviceFallback: "This device", switchPartialFailed: "Some inputs for {name} could not be switched: {errors}", switchComplete: "Switched {count} monitor(s) to {name}.",
  shortcutDuplicate: "Shortcut {shortcut} is assigned more than once.", shortcutRegistrationFailed: "Shortcut registration failed: {error}", unnamedDevice: "Device {input}",
} as const;

export type TranslationKey = keyof typeof en;
export type Messages = Partial<Record<TranslationKey, string>>;

const zhCN: Messages = {
  tagline:"显示器信号切换",devices:"设备管理",monitors:"显示器管理",settings:"设置",devicesDescription:"创建设备，为每个设备分配显示器端口和切换快捷键",monitorsDescription:"扫描显示器，并把每个物理接口分配给设备",settingsDescription:"配置 SoftKVM 的外观和系统行为",rescan:"重新扫描",scanning:"正在扫描显示器",scanningDescription:"正在通过 DDC/CI 读取物理显示器和输入源信息。部分显示器响应较慢，请稍候。",detecting:"检测中…",newDeviceName:"新设备名称",newDevicePlaceholder:"例如：PC 1、Xbox、Nintendo Switch",createDevice:"创建设备",noDevices:"还没有设备",noDevicesDescription:"先新建 PC、游戏机等设备，再到“显示器管理”把端口分配给它。",assignedMonitors:"已分配 {count} 台显示器",portMappings:"端口映射",notAssignedHint:"尚未分配，请前往显示器管理。",switchToDevice:"切换到此设备",noMonitorsMapped:"未扫描到显示器，设备端口映射可能暂时无法显示。",deleteDeviceTitle:"删除设备“{name}”？",deleteDeviceDescription:"这个操作会同时清除该设备在所有显示器上的端口分配和快捷键配置。显示器本身不会受到影响。",cancel:"取消",confirmDelete:"确认删除",noMonitors:"没有发现显示器",noMonitorsDescription:"确认显示器已连接且在 OSD 菜单中启用了 DDC/CI。",scanMonitors:"扫描显示器",inputsDetected:"已识别输入源",compatibilityMode:"兼容模式",monitorNumber:"显示器 {number}",currentInput:"当前 {input}",monitorName:"显示器名称",physicalChannel:"物理通道 {number}",compatibilityInputs:"扫描失败时的兼容输入源",compatibilityExpanded:"这些是常见候选值，可随时折叠。",compatibilityCollapsed:"已隐藏 {count} 个候选端口，点击展开。",unassignedDevice:"未分配",noAssignableDevices:"还没有可分配的设备，请先在设备管理中创建。",technicalInfo:"技术信息",noCapabilities:"显示器未返回 capabilities 字符串。",appearance:"外观",appearanceDescription:"选择应用的强调色，按钮、选中状态和焦点边框会同步更新。",themeColor:"主题色",themeCyan:"青色",themeBlue:"蓝色",themeEmerald:"绿色",themeOrange:"橙色",themeZinc:"中性黑",language:"语言",languageDescription:"选择界面语言；跟随系统会自动使用 Windows 的语言。",followSystem:"跟随系统",systemBehavior:"系统行为",systemBehaviorDescription:"控制 SoftKVM 如何随 Windows 运行。",autostart:"开机自动启动",autostartDescription:"登录 Windows 后自动运行 SoftKVM，让设备快捷键随时可用。",minimize:"最小化",close:"关闭",dismiss:"关闭提示",trayDevices:"切换设备",trayNoDevices:"暂无设备",trayShow:"显示 SoftKVM",trayQuit:"退出",traySyncFailed:"更新托盘菜单失败：{error}",pressShortcut:"请按组合键…",bindShortcut:"绑定快捷键",clearShortcut:"清除快捷键",scanNone:"没有找到可访问的物理显示器，请检查连接和显卡驱动。",scanComplete:"扫描完成，找到 {count} 台物理显示器。",autostartReadFailed:"读取开机启动状态失败：{error}",autostartChangeFailed:"修改开机启动失败：{error}",deviceNoRoutes:"{name} 还没有分配任何显示器端口。",deviceFallback:"该设备",switchPartialFailed:"{name} 部分切换失败：{errors}",switchComplete:"已将 {count} 台显示器切换到 {name}。",shortcutDuplicate:"快捷键 {shortcut} 被重复绑定。",shortcutRegistrationFailed:"快捷键注册失败：{error}",unnamedDevice:"设备 {input}"
};

const zhTW: Messages = {
  tagline:"螢幕訊號切換",devices:"裝置管理",monitors:"螢幕管理",settings:"設定",devicesDescription:"建立裝置，並為每個裝置指派螢幕輸入與快速鍵",monitorsDescription:"掃描螢幕並將每個實體輸入指派給裝置",settingsDescription:"設定 SoftKVM 的外觀與系統行為",rescan:"重新掃描",scanning:"正在掃描螢幕",scanningDescription:"正在透過 DDC/CI 讀取實體螢幕與輸入來源，請稍候。",detecting:"偵測中…",newDeviceName:"新裝置名稱",createDevice:"建立裝置",noDevices:"尚無裝置",noDevicesDescription:"先建立電腦或遊戲主機，再到螢幕管理指派輸入。",assignedMonitors:"已指派 {count} 台螢幕",portMappings:"輸入對應",notAssignedHint:"尚未指派，請前往螢幕管理。",switchToDevice:"切換到此裝置",deleteDeviceTitle:"刪除「{name}」？",deleteDeviceDescription:"這也會移除該裝置的輸入指派與快速鍵，但不影響螢幕。",cancel:"取消",confirmDelete:"確認刪除",noMonitors:"找不到螢幕",noMonitorsDescription:"請確認螢幕已連線且 OSD 中已啟用 DDC/CI。",scanMonitors:"掃描螢幕",inputsDetected:"已識別輸入來源",compatibilityMode:"相容模式",monitorNumber:"螢幕 {number}",currentInput:"目前 {input}",monitorName:"螢幕名稱",physicalChannel:"實體通道 {number}",compatibilityInputs:"掃描失敗時的相容輸入",compatibilityExpanded:"這些是常見候選值，可隨時收合。",compatibilityCollapsed:"已隱藏 {count} 個候選輸入，按一下展開。",unassignedDevice:"未指派",noAssignableDevices:"尚無可指派的裝置，請先建立裝置。",technicalInfo:"技術資訊",noCapabilities:"螢幕未回傳 capabilities 字串。",appearance:"外觀",appearanceDescription:"選擇按鈕、選取狀態與焦點框使用的強調色。",themeColor:"主題色",themeCyan:"青色",themeBlue:"藍色",themeEmerald:"綠色",themeOrange:"橙色",themeZinc:"中性黑",language:"語言",languageDescription:"選擇介面語言；跟隨系統會使用 Windows 語言。",followSystem:"跟隨系統",systemBehavior:"系統行為",systemBehaviorDescription:"控制 SoftKVM 如何隨 Windows 執行。",autostart:"開機自動啟動",autostartDescription:"登入 Windows 後自動執行 SoftKVM。",minimize:"最小化",close:"關閉",dismiss:"關閉提示",trayDevices:"切換裝置",trayNoDevices:"暫無裝置",trayShow:"顯示 SoftKVM",trayQuit:"結束",pressShortcut:"請按快速鍵…",bindShortcut:"設定快速鍵",clearShortcut:"清除快速鍵"
};

const common: Record<Exclude<AppLocale, "system" | "zh-CN" | "zh-TW" | "en">, Messages> = {
  ja:{tagline:"モニター入力切替",devices:"デバイス",monitors:"モニター",settings:"設定",devicesDescription:"デバイスを作成し、入力端子とショートカットを割り当てます",monitorsDescription:"モニターをスキャンし、各入力をデバイスに割り当てます",settingsDescription:"SoftKVM の外観と動作を設定します",rescan:"再スキャン",scanning:"モニターをスキャン中",detecting:"検出中…",newDeviceName:"新しいデバイス名",createDevice:"デバイスを作成",noDevices:"デバイスがありません",assignedMonitors:"{count} 台のモニターに割り当て済み",portMappings:"入力マッピング",switchToDevice:"このデバイスに切替",cancel:"キャンセル",confirmDelete:"削除",noMonitors:"モニターが見つかりません",scanMonitors:"モニターをスキャン",inputsDetected:"入力を検出",compatibilityMode:"互換モード",monitorNumber:"モニター {number}",currentInput:"現在 {input}",unassignedDevice:"未割り当て",technicalInfo:"技術情報",appearance:"外観",themeColor:"アクセントカラー",language:"言語",languageDescription:"表示言語を選択します。システム設定では Windows に従います。",followSystem:"システム言語",systemBehavior:"システム動作",autostart:"起動時に実行",minimize:"最小化",close:"閉じる",trayDevices:"デバイスを切替",trayNoDevices:"デバイスなし",trayShow:"SoftKVMを表示",trayQuit:"終了",pressShortcut:"ショートカットを入力…",bindShortcut:"ショートカットを設定",clearShortcut:"ショートカットを解除"},
  ko:{tagline:"모니터 입력 전환",devices:"장치",monitors:"모니터",settings:"설정",devicesDescription:"장치를 만들고 모니터 입력과 단축키를 할당합니다",monitorsDescription:"모니터를 검색하고 각 입력을 장치에 할당합니다",settingsDescription:"SoftKVM의 모양과 동작을 설정합니다",rescan:"다시 검색",scanning:"모니터 검색 중",detecting:"검색 중…",newDeviceName:"새 장치 이름",createDevice:"장치 만들기",noDevices:"장치가 없습니다",assignedMonitors:"모니터 {count}대에 할당됨",portMappings:"입력 매핑",switchToDevice:"이 장치로 전환",cancel:"취소",confirmDelete:"삭제",noMonitors:"모니터를 찾지 못했습니다",scanMonitors:"모니터 검색",inputsDetected:"입력 감지됨",compatibilityMode:"호환 모드",monitorNumber:"모니터 {number}",currentInput:"현재 {input}",unassignedDevice:"할당 안 됨",technicalInfo:"기술 정보",appearance:"모양",themeColor:"강조 색상",language:"언어",languageDescription:"인터페이스 언어를 선택합니다. 시스템은 Windows 언어를 따릅니다.",followSystem:"시스템 언어",systemBehavior:"시스템 동작",autostart:"시작 시 실행",minimize:"최소화",close:"닫기",trayDevices:"장치 전환",trayNoDevices:"장치 없음",trayShow:"SoftKVM 표시",trayQuit:"종료",pressShortcut:"단축키를 누르세요…",bindShortcut:"단축키 설정",clearShortcut:"단축키 지우기"},
  es:{tagline:"Cambio de entrada del monitor",devices:"Dispositivos",monitors:"Monitores",settings:"Ajustes",devicesDescription:"Crea dispositivos y asigna entradas y atajos",monitorsDescription:"Busca monitores y asigna cada entrada a un dispositivo",settingsDescription:"Configura el aspecto y funcionamiento de SoftKVM",rescan:"Buscar de nuevo",scanning:"Buscando monitores",detecting:"Detectando…",newDeviceName:"Nombre del dispositivo",createDevice:"Crear dispositivo",noDevices:"Aún no hay dispositivos",assignedMonitors:"Asignado a {count} monitor(es)",portMappings:"Asignación de entradas",switchToDevice:"Cambiar a este dispositivo",cancel:"Cancelar",confirmDelete:"Eliminar",noMonitors:"No se encontraron monitores",scanMonitors:"Buscar monitores",inputsDetected:"Entradas detectadas",compatibilityMode:"Modo compatible",monitorNumber:"Monitor {number}",currentInput:"Actual {input}",unassignedDevice:"Sin asignar",technicalInfo:"Información técnica",appearance:"Apariencia",themeColor:"Color de énfasis",language:"Idioma",languageDescription:"Elige el idioma. Sistema sigue el idioma de Windows.",followSystem:"Idioma del sistema",systemBehavior:"Comportamiento del sistema",autostart:"Iniciar al encender",minimize:"Minimizar",close:"Cerrar",trayDevices:"Cambiar dispositivo",trayNoDevices:"Sin dispositivos",trayShow:"Mostrar SoftKVM",trayQuit:"Salir",pressShortcut:"Pulsa un atajo…",bindShortcut:"Definir atajo",clearShortcut:"Borrar atajo"},
  fr:{tagline:"Changement d’entrée du moniteur",devices:"Appareils",monitors:"Moniteurs",settings:"Paramètres",devicesDescription:"Créez des appareils et attribuez les entrées et raccourcis",monitorsDescription:"Analysez les moniteurs et attribuez chaque entrée",settingsDescription:"Configurez l’apparence et le fonctionnement de SoftKVM",rescan:"Réanalyser",scanning:"Analyse des moniteurs",detecting:"Détection…",newDeviceName:"Nom du nouvel appareil",createDevice:"Créer l’appareil",noDevices:"Aucun appareil",assignedMonitors:"Attribué à {count} moniteur(s)",portMappings:"Mappage des entrées",switchToDevice:"Basculer vers cet appareil",cancel:"Annuler",confirmDelete:"Supprimer",noMonitors:"Aucun moniteur trouvé",scanMonitors:"Analyser",inputsDetected:"Entrées détectées",compatibilityMode:"Mode compatible",monitorNumber:"Moniteur {number}",currentInput:"Actuelle {input}",unassignedDevice:"Non attribué",technicalInfo:"Informations techniques",appearance:"Apparence",themeColor:"Couleur d’accentuation",language:"Langue",languageDescription:"Choisissez la langue. Système suit la langue de Windows.",followSystem:"Langue du système",systemBehavior:"Comportement système",autostart:"Lancer au démarrage",minimize:"Réduire",close:"Fermer",trayDevices:"Changer d’appareil",trayNoDevices:"Aucun appareil",trayShow:"Afficher SoftKVM",trayQuit:"Quitter",pressShortcut:"Appuyez sur un raccourci…",bindShortcut:"Définir un raccourci",clearShortcut:"Effacer le raccourci"},
  de:{tagline:"Monitor-Eingang umschalten",devices:"Geräte",monitors:"Monitore",settings:"Einstellungen",devicesDescription:"Geräte erstellen und Eingänge sowie Tastenkürzel zuweisen",monitorsDescription:"Monitore suchen und Eingänge Geräten zuweisen",settingsDescription:"Aussehen und Verhalten von SoftKVM konfigurieren",rescan:"Erneut suchen",scanning:"Monitore werden gesucht",detecting:"Erkennung…",newDeviceName:"Neuer Gerätename",createDevice:"Gerät erstellen",noDevices:"Noch keine Geräte",assignedMonitors:"{count} Monitor(en) zugewiesen",portMappings:"Eingangszuordnung",switchToDevice:"Zu diesem Gerät wechseln",cancel:"Abbrechen",confirmDelete:"Löschen",noMonitors:"Keine Monitore gefunden",scanMonitors:"Monitore suchen",inputsDetected:"Eingänge erkannt",compatibilityMode:"Kompatibilitätsmodus",monitorNumber:"Monitor {number}",currentInput:"Aktuell {input}",unassignedDevice:"Nicht zugewiesen",technicalInfo:"Technische Informationen",appearance:"Darstellung",themeColor:"Akzentfarbe",language:"Sprache",languageDescription:"Oberflächensprache wählen. System folgt Windows.",followSystem:"Systemsprache",systemBehavior:"Systemverhalten",autostart:"Beim Start ausführen",minimize:"Minimieren",close:"Schließen",trayDevices:"Gerät wechseln",trayNoDevices:"Keine Geräte",trayShow:"SoftKVM anzeigen",trayQuit:"Beenden",pressShortcut:"Tastenkürzel drücken…",bindShortcut:"Tastenkürzel festlegen",clearShortcut:"Tastenkürzel löschen"},
  "pt-BR":{tagline:"Alternância de entrada do monitor",devices:"Dispositivos",monitors:"Monitores",settings:"Configurações",devicesDescription:"Crie dispositivos e atribua entradas e atalhos",monitorsDescription:"Procure monitores e atribua cada entrada",settingsDescription:"Configure a aparência e o funcionamento do SoftKVM",rescan:"Procurar novamente",scanning:"Procurando monitores",detecting:"Detectando…",newDeviceName:"Nome do dispositivo",createDevice:"Criar dispositivo",noDevices:"Nenhum dispositivo",assignedMonitors:"Atribuído a {count} monitor(es)",portMappings:"Mapeamento de entradas",switchToDevice:"Alternar para este dispositivo",cancel:"Cancelar",confirmDelete:"Excluir",noMonitors:"Nenhum monitor encontrado",scanMonitors:"Procurar monitores",inputsDetected:"Entradas detectadas",compatibilityMode:"Modo de compatibilidade",monitorNumber:"Monitor {number}",currentInput:"Atual {input}",unassignedDevice:"Não atribuído",technicalInfo:"Informações técnicas",appearance:"Aparência",themeColor:"Cor de destaque",language:"Idioma",languageDescription:"Escolha o idioma. Sistema segue o idioma do Windows.",followSystem:"Idioma do sistema",systemBehavior:"Comportamento do sistema",autostart:"Iniciar com o sistema",minimize:"Minimizar",close:"Fechar",trayDevices:"Alternar dispositivo",trayNoDevices:"Nenhum dispositivo",trayShow:"Mostrar SoftKVM",trayQuit:"Sair",pressShortcut:"Pressione um atalho…",bindShortcut:"Definir atalho",clearShortcut:"Limpar atalho"},
  ru:{tagline:"Переключение входа монитора",devices:"Устройства",monitors:"Мониторы",settings:"Настройки",devicesDescription:"Создавайте устройства и назначайте входы и сочетания клавиш",monitorsDescription:"Найдите мониторы и назначьте каждый вход устройству",settingsDescription:"Настройте внешний вид и работу SoftKVM",rescan:"Сканировать снова",scanning:"Поиск мониторов",detecting:"Обнаружение…",newDeviceName:"Имя устройства",createDevice:"Создать устройство",noDevices:"Устройств пока нет",assignedMonitors:"Назначено мониторов: {count}",portMappings:"Назначение входов",switchToDevice:"Переключить на устройство",cancel:"Отмена",confirmDelete:"Удалить",noMonitors:"Мониторы не найдены",scanMonitors:"Найти мониторы",inputsDetected:"Входы обнаружены",compatibilityMode:"Режим совместимости",monitorNumber:"Монитор {number}",currentInput:"Текущий {input}",unassignedDevice:"Не назначено",technicalInfo:"Техническая информация",appearance:"Оформление",themeColor:"Акцентный цвет",language:"Язык",languageDescription:"Выберите язык. Системный использует язык Windows.",followSystem:"Системный язык",systemBehavior:"Поведение системы",autostart:"Запускать при входе",minimize:"Свернуть",close:"Закрыть",trayDevices:"Переключить устройство",trayNoDevices:"Нет устройств",trayShow:"Показать SoftKVM",trayQuit:"Выйти",pressShortcut:"Нажмите сочетание…",bindShortcut:"Задать сочетание",clearShortcut:"Очистить сочетание"},
  ar:{tagline:"تبديل مدخل الشاشة",devices:"الأجهزة",monitors:"الشاشات",settings:"الإعدادات",devicesDescription:"أنشئ الأجهزة وعيّن المداخل والاختصارات",monitorsDescription:"افحص الشاشات وعيّن كل مدخل لجهاز",settingsDescription:"اضبط مظهر SoftKVM وسلوكه",rescan:"إعادة الفحص",scanning:"جارٍ فحص الشاشات",detecting:"جارٍ الاكتشاف…",newDeviceName:"اسم الجهاز الجديد",createDevice:"إنشاء جهاز",noDevices:"لا توجد أجهزة",assignedMonitors:"معيّن إلى {count} شاشة",portMappings:"تعيين المداخل",switchToDevice:"التبديل إلى هذا الجهاز",cancel:"إلغاء",confirmDelete:"حذف",noMonitors:"لم يتم العثور على شاشات",scanMonitors:"فحص الشاشات",inputsDetected:"تم اكتشاف المداخل",compatibilityMode:"وضع التوافق",monitorNumber:"الشاشة {number}",currentInput:"الحالي {input}",unassignedDevice:"غير معيّن",technicalInfo:"معلومات تقنية",appearance:"المظهر",themeColor:"لون التمييز",language:"اللغة",languageDescription:"اختر لغة الواجهة. يتبع خيار النظام لغة Windows.",followSystem:"لغة النظام",systemBehavior:"سلوك النظام",autostart:"التشغيل عند البدء",minimize:"تصغير",close:"إغلاق",trayDevices:"تبديل الجهاز",trayNoDevices:"لا توجد أجهزة",trayShow:"إظهار SoftKVM",trayQuit:"خروج",pressShortcut:"اضغط اختصارًا…",bindShortcut:"تعيين اختصار",clearShortcut:"مسح الاختصار"},
  hi:{tagline:"मॉनिटर इनपुट बदलें",devices:"डिवाइस",monitors:"मॉनिटर",settings:"सेटिंग्स",devicesDescription:"डिवाइस बनाएँ और इनपुट व शॉर्टकट असाइन करें",monitorsDescription:"मॉनिटर स्कैन करें और हर इनपुट असाइन करें",settingsDescription:"SoftKVM का रूप और व्यवहार कॉन्फ़िगर करें",rescan:"फिर स्कैन करें",scanning:"मॉनिटर स्कैन हो रहे हैं",detecting:"पता लगाया जा रहा है…",newDeviceName:"नए डिवाइस का नाम",createDevice:"डिवाइस बनाएँ",noDevices:"अभी कोई डिवाइस नहीं",assignedMonitors:"{count} मॉनिटर असाइन",portMappings:"इनपुट मैपिंग",switchToDevice:"इस डिवाइस पर जाएँ",cancel:"रद्द करें",confirmDelete:"हटाएँ",noMonitors:"कोई मॉनिटर नहीं मिला",scanMonitors:"मॉनिटर स्कैन करें",inputsDetected:"इनपुट मिले",compatibilityMode:"संगतता मोड",monitorNumber:"मॉनिटर {number}",currentInput:"वर्तमान {input}",unassignedDevice:"असाइन नहीं",technicalInfo:"तकनीकी जानकारी",appearance:"दिखावट",themeColor:"मुख्य रंग",language:"भाषा",languageDescription:"इंटरफ़ेस भाषा चुनें। सिस्टम Windows की भाषा अपनाता है।",followSystem:"सिस्टम भाषा",systemBehavior:"सिस्टम व्यवहार",autostart:"स्टार्टअप पर चलाएँ",minimize:"छोटा करें",close:"बंद करें",trayDevices:"डिवाइस बदलें",trayNoDevices:"कोई डिवाइस नहीं",trayShow:"SoftKVM दिखाएँ",trayQuit:"बाहर निकलें",pressShortcut:"शॉर्टकट दबाएँ…",bindShortcut:"शॉर्टकट सेट करें",clearShortcut:"शॉर्टकट हटाएँ"},
  id:{tagline:"Peralihan input monitor",devices:"Perangkat",monitors:"Monitor",settings:"Pengaturan",devicesDescription:"Buat perangkat lalu tetapkan input dan pintasan",monitorsDescription:"Pindai monitor dan tetapkan setiap input",settingsDescription:"Atur tampilan dan perilaku SoftKVM",rescan:"Pindai lagi",scanning:"Memindai monitor",detecting:"Mendeteksi…",newDeviceName:"Nama perangkat baru",createDevice:"Buat perangkat",noDevices:"Belum ada perangkat",assignedMonitors:"Ditetapkan ke {count} monitor",portMappings:"Pemetaan input",switchToDevice:"Beralih ke perangkat ini",cancel:"Batal",confirmDelete:"Hapus",noMonitors:"Monitor tidak ditemukan",scanMonitors:"Pindai monitor",inputsDetected:"Input terdeteksi",compatibilityMode:"Mode kompatibilitas",monitorNumber:"Monitor {number}",currentInput:"Saat ini {input}",unassignedDevice:"Belum ditetapkan",technicalInfo:"Informasi teknis",appearance:"Tampilan",themeColor:"Warna aksen",language:"Bahasa",languageDescription:"Pilih bahasa antarmuka. Sistem mengikuti bahasa Windows.",followSystem:"Bahasa sistem",systemBehavior:"Perilaku sistem",autostart:"Jalankan saat mulai",minimize:"Minimalkan",close:"Tutup",trayDevices:"Ganti perangkat",trayNoDevices:"Tidak ada perangkat",trayShow:"Tampilkan SoftKVM",trayQuit:"Keluar",pressShortcut:"Tekan pintasan…",bindShortcut:"Atur pintasan",clearShortcut:"Hapus pintasan"},
  tr:{tagline:"Monitör girişi değiştirme",devices:"Cihazlar",monitors:"Monitörler",settings:"Ayarlar",devicesDescription:"Cihaz oluşturup girişleri ve kısayolları atayın",monitorsDescription:"Monitörleri tarayıp her girişi bir cihaza atayın",settingsDescription:"SoftKVM görünümünü ve davranışını yapılandırın",rescan:"Yeniden tara",scanning:"Monitörler taranıyor",detecting:"Algılanıyor…",newDeviceName:"Yeni cihaz adı",createDevice:"Cihaz oluştur",noDevices:"Henüz cihaz yok",assignedMonitors:"{count} monitöre atandı",portMappings:"Giriş eşlemeleri",switchToDevice:"Bu cihaza geç",cancel:"İptal",confirmDelete:"Sil",noMonitors:"Monitör bulunamadı",scanMonitors:"Monitörleri tara",inputsDetected:"Girişler algılandı",compatibilityMode:"Uyumluluk modu",monitorNumber:"Monitör {number}",currentInput:"Geçerli {input}",unassignedDevice:"Atanmamış",technicalInfo:"Teknik bilgiler",appearance:"Görünüm",themeColor:"Vurgu rengi",language:"Dil",languageDescription:"Arayüz dilini seçin. Sistem Windows dilini izler.",followSystem:"Sistem dili",systemBehavior:"Sistem davranışı",autostart:"Başlangıçta çalıştır",minimize:"Küçült",close:"Kapat",trayDevices:"Cihaz değiştir",trayNoDevices:"Cihaz yok",trayShow:"SoftKVM'yi göster",trayQuit:"Çıkış",pressShortcut:"Kısayola basın…",bindShortcut:"Kısayol ata",clearShortcut:"Kısayolu temizle"},
  it:{tagline:"Cambio ingresso monitor",devices:"Dispositivi",monitors:"Monitor",settings:"Impostazioni",devicesDescription:"Crea dispositivi e assegna ingressi e scorciatoie",monitorsDescription:"Cerca i monitor e assegna ogni ingresso",settingsDescription:"Configura l’aspetto e il funzionamento di SoftKVM",rescan:"Cerca di nuovo",scanning:"Ricerca dei monitor",detecting:"Rilevamento…",newDeviceName:"Nome nuovo dispositivo",createDevice:"Crea dispositivo",noDevices:"Nessun dispositivo",assignedMonitors:"Assegnato a {count} monitor",portMappings:"Mappatura ingressi",switchToDevice:"Passa a questo dispositivo",cancel:"Annulla",confirmDelete:"Elimina",noMonitors:"Nessun monitor trovato",scanMonitors:"Cerca monitor",inputsDetected:"Ingressi rilevati",compatibilityMode:"Modalità compatibilità",monitorNumber:"Monitor {number}",currentInput:"Attuale {input}",unassignedDevice:"Non assegnato",technicalInfo:"Informazioni tecniche",appearance:"Aspetto",themeColor:"Colore principale",language:"Lingua",languageDescription:"Scegli la lingua. Sistema segue la lingua di Windows.",followSystem:"Lingua di sistema",systemBehavior:"Comportamento sistema",autostart:"Avvia all’accesso",minimize:"Riduci",close:"Chiudi",trayDevices:"Cambia dispositivo",trayNoDevices:"Nessun dispositivo",trayShow:"Mostra SoftKVM",trayQuit:"Esci",pressShortcut:"Premi una scorciatoia…",bindShortcut:"Imposta scorciatoia",clearShortcut:"Cancella scorciatoia"},
  pl:{tagline:"Przełączanie wejścia monitora",devices:"Urządzenia",monitors:"Monitory",settings:"Ustawienia",devicesDescription:"Twórz urządzenia i przypisuj wejścia oraz skróty",monitorsDescription:"Wyszukaj monitory i przypisz każde wejście",settingsDescription:"Skonfiguruj wygląd i działanie SoftKVM",rescan:"Skanuj ponownie",scanning:"Skanowanie monitorów",detecting:"Wykrywanie…",newDeviceName:"Nazwa nowego urządzenia",createDevice:"Utwórz urządzenie",noDevices:"Brak urządzeń",assignedMonitors:"Przypisano do {count} monitorów",portMappings:"Mapowanie wejść",switchToDevice:"Przełącz na to urządzenie",cancel:"Anuluj",confirmDelete:"Usuń",noMonitors:"Nie znaleziono monitorów",scanMonitors:"Skanuj monitory",inputsDetected:"Wykryto wejścia",compatibilityMode:"Tryb zgodności",monitorNumber:"Monitor {number}",currentInput:"Bieżące {input}",unassignedDevice:"Nieprzypisane",technicalInfo:"Informacje techniczne",appearance:"Wygląd",themeColor:"Kolor akcentu",language:"Język",languageDescription:"Wybierz język. Systemowy używa języka Windows.",followSystem:"Język systemu",systemBehavior:"Zachowanie systemu",autostart:"Uruchamiaj przy starcie",minimize:"Minimalizuj",close:"Zamknij",trayDevices:"Przełącz urządzenie",trayNoDevices:"Brak urządzeń",trayShow:"Pokaż SoftKVM",trayQuit:"Zakończ",pressShortcut:"Naciśnij skrót…",bindShortcut:"Ustaw skrót",clearShortcut:"Wyczyść skrót"},
  nl:{tagline:"Monitorinvoer wisselen",devices:"Apparaten",monitors:"Monitoren",settings:"Instellingen",devicesDescription:"Maak apparaten en wijs ingangen en sneltoetsen toe",monitorsDescription:"Scan monitoren en wijs elke ingang toe",settingsDescription:"Stel het uiterlijk en gedrag van SoftKVM in",rescan:"Opnieuw scannen",scanning:"Monitoren scannen",detecting:"Detecteren…",newDeviceName:"Naam nieuw apparaat",createDevice:"Apparaat maken",noDevices:"Nog geen apparaten",assignedMonitors:"Aan {count} monitor(en) toegewezen",portMappings:"Ingangstoewijzing",switchToDevice:"Naar dit apparaat schakelen",cancel:"Annuleren",confirmDelete:"Verwijderen",noMonitors:"Geen monitoren gevonden",scanMonitors:"Monitoren scannen",inputsDetected:"Ingangen gedetecteerd",compatibilityMode:"Compatibiliteitsmodus",monitorNumber:"Monitor {number}",currentInput:"Huidig {input}",unassignedDevice:"Niet toegewezen",technicalInfo:"Technische informatie",appearance:"Weergave",themeColor:"Accentkleur",language:"Taal",languageDescription:"Kies de interfacetaal. Systeem volgt Windows.",followSystem:"Systeemtaal",systemBehavior:"Systeemgedrag",autostart:"Starten bij aanmelden",minimize:"Minimaliseren",close:"Sluiten",trayDevices:"Apparaat wisselen",trayNoDevices:"Geen apparaten",trayShow:"SoftKVM tonen",trayQuit:"Afsluiten",pressShortcut:"Druk een sneltoets…",bindShortcut:"Sneltoets instellen",clearShortcut:"Sneltoets wissen"},
  vi:{tagline:"Chuyển đầu vào màn hình",devices:"Thiết bị",monitors:"Màn hình",settings:"Cài đặt",devicesDescription:"Tạo thiết bị rồi gán đầu vào và phím tắt",monitorsDescription:"Quét màn hình và gán từng đầu vào",settingsDescription:"Cấu hình giao diện và hoạt động của SoftKVM",rescan:"Quét lại",scanning:"Đang quét màn hình",detecting:"Đang phát hiện…",newDeviceName:"Tên thiết bị mới",createDevice:"Tạo thiết bị",noDevices:"Chưa có thiết bị",assignedMonitors:"Đã gán cho {count} màn hình",portMappings:"Ánh xạ đầu vào",switchToDevice:"Chuyển sang thiết bị này",cancel:"Hủy",confirmDelete:"Xóa",noMonitors:"Không tìm thấy màn hình",scanMonitors:"Quét màn hình",inputsDetected:"Đã phát hiện đầu vào",compatibilityMode:"Chế độ tương thích",monitorNumber:"Màn hình {number}",currentInput:"Hiện tại {input}",unassignedDevice:"Chưa gán",technicalInfo:"Thông tin kỹ thuật",appearance:"Giao diện",themeColor:"Màu nhấn",language:"Ngôn ngữ",languageDescription:"Chọn ngôn ngữ giao diện. Hệ thống theo ngôn ngữ Windows.",followSystem:"Ngôn ngữ hệ thống",systemBehavior:"Hoạt động hệ thống",autostart:"Chạy khi khởi động",minimize:"Thu nhỏ",close:"Đóng",trayDevices:"Chuyển thiết bị",trayNoDevices:"Không có thiết bị",trayShow:"Hiện SoftKVM",trayQuit:"Thoát",pressShortcut:"Nhấn phím tắt…",bindShortcut:"Đặt phím tắt",clearShortcut:"Xóa phím tắt"}
};

export const resources: Record<Exclude<AppLocale, "system">, Messages> = { en, "zh-CN": zhCN, "zh-TW": zhTW, ...common };

export const localeOptions: Array<{ value: AppLocale; label: string }> = [
  {value:"system",label:"System / 系统"},{value:"zh-CN",label:"简体中文"},{value:"zh-TW",label:"繁體中文"},{value:"en",label:"English"},{value:"ja",label:"日本語"},{value:"ko",label:"한국어"},{value:"es",label:"Español"},{value:"fr",label:"Français"},{value:"de",label:"Deutsch"},{value:"pt-BR",label:"Português (Brasil)"},{value:"ru",label:"Русский"},{value:"ar",label:"العربية"},{value:"hi",label:"हिन्दी"},{value:"id",label:"Bahasa Indonesia"},{value:"tr",label:"Türkçe"},{value:"it",label:"Italiano"},{value:"pl",label:"Polski"},{value:"nl",label:"Nederlands"},{value:"vi",label:"Tiếng Việt"}
];
